title: Home

resources:
  - url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.1.2
    type: js

views:
  - path: default_view
    title: Home
    icon: 'mdi:home'
    badges:
      - binary_sensor.justin_presence
      - binary_sensor.jenni_presence
      - binary_sensor.jayden_presence
      - sensor.sunset_time
      - sensor.workday_alarm
      - sensor.weekend_alarm
    cards:
      - type: glance
        entities:
          - entity: light.fairy_lights
            tap_action:
              action: toggle
          - entity: light.fish_light
            tap_action:
              action: toggle
          - entity: light.betta_light
            tap_action:
              action: toggle
          - entity: switch.justins_pc
            tap_action:
              action: toggle
          #- entity: switch.christmas_wreath
          #  name: Wreath
          #  tap_action:
          #    action: toggle
          #- entity: lock.front_door
          #  tap_action:
          #    action: toggle
          - entity: switch.bedroom_air_purifier
            name: Air Purifier
            tap_action:
              action: toggle
          #- entity: switch.bedroom_fan
          #  name: Fan
          #  tap_action:
          #    action: toggle
          - entity: media_player.vizio_smartcast
            tap_action:
              action: toggle
          - entity: media_player.denon_avr_x1300w
            tap_action:
              action: toggle
      - type: glance
        entities:
          - entity: sensor.fish_fed
            tap_action:
              action: call-service
              service: input_boolean.toggle
              service_data:
                entity_id: input_boolean.fish_fed_tracker
          - entity: sensor.plants_watered
            tap_action:
              action: call-service
              service: input_boolean.toggle
              service_data:
                entity_id: input_boolean.plants_watered_tracker
      ## Media Control ##
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: input_select.media_select
                name: Input
              - entity: input_number.receiver_audio_volume
                name: Receiver Volume
              - entity: input_number.chromecast_audio_volume
                name: Chromecast Volume
          - type: conditional
            conditions:
              - entity: media_player.vizio_smartcast
                state: 'on'
            card:
              type: entities
              entities:
                - media_player.vizio_smartcast
          - type: conditional
            conditions:
              - entity: media_player.vizio_smartcast
                state: 'playing'
            card:
              type: media-control
              entities:
                - media_player.vizio_smartcast
          - type: conditional
            conditions:
              - entity: media_player.bedroom_tv
                state: 'playing'
            card:
              type: entities
              entities:
                - media_player.bedroom_tv
          - type: vertical-stack
            cards:
              - type: conditional
                conditions:
                  - entity: media_player.home_audio
                    state: 'playing'
                card:
                  type: entities
                  entities:
                    - sensor.album_art
              - type: conditional
                conditions:
                  - entity: media_player.fake_home_audio
                    state: 'playing'
                card:
                  type: entities
                  entities:
                    - sensor.album_art
              - type: conditional
                conditions:
                  - entity: media_player.master_suite_audio
                    state: 'playing'
                card:
                  type: entities
                  entities:
                    - sensor.album_art
              - type: conditional
                conditions:
                  - entity: media_player.mpd
                    state: 'playing'
                card:
                  type: entities
                  entities:
                    - media_player.mpd
          - type: conditional
            conditions:
              - entity: media_player.home_audio
                state: 'playing'
            card:
              type: entities
              entities:
                - media_player.home_audio
      ## Lights ##
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.kitchen
              - type: light
                entity: light.living_room_lamp
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.bedroom
              - type: light
                entity: light.scrub_room
      - type: weather-forecast
        entity: weather.dark_sky
  - path: alarms
    title: Alarms
    icon: mdi:alarm
    badges:
      - sensor.workday_alarm
      - sensor.weekend_alarm
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - input_boolean.workday_alarm
              - input_number.workday_hours
              - input_number.workday_minutes
          - type: entities
            entities:
              - input_boolean.weekend_alarm
              - input_number.weekend_hours
              - input_number.weekend_minutes
  - path: automations
    title: Automations
    icon: mdi:code-braces
    cards:
      - type: entities
        entities:
          - automation.arrive_home_jenni
          - automation.arrive_home_justin
          - automation.cast_music_when_playing_from_mpd
          - automation.casting_started_1
          - automation.casting_started_2
          - automation.leave_home_jenni
          - automation.leave_home_justin
          - automation.media_input_select_changed
          - automation.chromecast_volume_slider_moved
          - automation.receiver_volume_slider_moved
          - automation.music_started_1
          - automation.music_started_2
          - automation.night_no_one_home
          - automation.restart_stream
          - automation.stop_mpd_when_other_device_casting
          - automation.sunset
          #- automation.update_google_assistant
          - automation.update_led_strip_colour_when_hue_colour_changed
          - automation.periodically_change_the_led_strip_to_a_random_colour
          #- automation.its_christmas
      - type: entities
        entities:
          - script.be_right_back
          - script.bedtime
          - script.led_strip_turn_on
          - script.morning
          - script.next_track
          - script.pause_music
          - script.play_all_music
          - script.play_chill_music
          - script.play_music
          - script.restart_mopidy_stream
          - script.shutoff
          - script.switch_to_audio
          - script.switch_to_chromecast
          - script.volume_down
          - script.volume_up
  - path: media
    title: Media Control
    icon: mdi:music
    cards:
      - type: entities
        entities:
          - input_number.living_room_audio_volume
          - input_number.bedroom_audio_volume
          - input_number.bathroom_audio_volume
          - input_number.main_bathroom_audio_volume
          - input_select.media_output_select
      - type: media-control
        entity: media_player.bedroom_audio
      - type: media-control
        entity: media_player.bedroom_speaker
      - type: media-control
        entity: media_player.bathroom_speaker
      - type: media-control
        entity: media_player.main_bathroom_speaker
      - type: media-control
        entity: media_player.living_room_audio
      - type: media-control
        entity: media_player.living_room_speaker
      - type: media-control
        entity: media_player.denon_avr_x1300w
  - path: video
    title: TV
    icon: mdi:youtube
    cards:
      - type: custom:upcoming-media-card
        entity: sensor.sonarr_upcoming_media
