title: Home

views:
  - path: default_view
    title: Home
    icon: 'mdi:home'
    badges:
      - binary_sensor.justin_presence
      - binary_sensor.jenni_presence
      - sensor.sunset_time
      - sensor.workday_alarm
      - sensor.weekend_alarm
    cards:
      - type: glance
        entities:
          - entity: light.fairy_lights
            tap_action:
              action: toggle
          - entity: light.fish_light
            tap_action:
              action: toggle
          - entity: light.betta_light
            tap_action:
              action: toggle
          - entity: switch.justins_pc
            tap_action:
              action: toggle
          #- entity: switch.christmas_wreath
          #  name: Wreath
          #  tap_action:
          #    action: toggle
          - entity: lock.front_door
            tap_action:
              action: toggle
          - entity: switch.air_purifier
            name: Air Purifier
            tap_action:
              action: toggle
          #- entity: switch.bedroom_fan
          #  name: Fan
          #  tap_action:
          #    action: toggle
          - entity: input_boolean.bedtime
            tap_action:
              action: toggle
            name: Bedtime
          - entity: input_boolean.enable_presence_automations
            tap_action:
              action: toggle
            name: Presence
          - entity: script.play_all_music
            name: All Music
            icon: mdi:music
            show_state: false
            tap_action:
              action: toggle
          - entity: script.play_chill_music
            name: Chill Music
            icon: mdi:music
            show_state: false
            tap_action:
              action: toggle
      ## Media Control ##
      - type: vertical-stack
        cards:
          - type: custom:mini-media-player
            entity: media_player.denon_avr_x1300w
            icon: mdi:audio-video
            group: true
            hide:
              source: true
              play_pause: true
            shortcuts:
              buttons:
                - name: Music
                  type: service
                  id: media_player.select_source
                  data:
                    entity_id: media_player.denon_avr_x1300w
                    source: CastAudio
                - name: PC
                  type: service
                  id: media_player.select_source
                  data:
                    entity_id: media_player.denon_avr_x1300w
                    source: PC
                - name: Shield
                  type: service
                  id: media_player.select_source
                  data:
                    entity_id: media_player.denon_avr_x1300w
                    source: Shield
                - name: Switch
                  type: service
                  id: media_player.select_source
                  data:
                    entity_id: media_player.denon_avr_x1300w
                    source: Switch
          - type: custom:mini-media-player
            entity: media_player.vizio
            artwork: cover
            icon: mdi:television
            group: true
            hide:
              info: true
              volume: true
              controls: true
          - type: entities
            entities:
              - input_select.media_output_select
          - type: conditional
            conditions:
              - entity: media_player.shield
                state: 'idle'
            card:
              type: entities
              entities:
                - media_player.shield
          - type: conditional
            conditions:
              - entity: media_player.shield
                state: 'playing'
            card:
              type: custom:mini-media-player
              entity: media_player.shield
              artwork: cover
          - type: conditional
            conditions:
              - entity: media_player.master_bedroom_tv
                state: 'playing'
            card:
              type: custom:mini-media-player
              entity: media_player.master_bedroom_tv
              artwork: cover
          - type: conditional
            conditions:
              - entity: media_player.home_audio
                state: 'playing'
            card:
              type: custom:mini-media-player
              entity: media_player.home_audio
              artwork: cover
          - type: conditional
            conditions:
              - entity: media_player.master_suite_audio
                state: 'playing'
            card:
              type: custom:mini-media-player
              entity: media_player.master_suite_audio
              artwork: cover
          - type: conditional
            conditions:
              - entity: media_player.master_bedroom_audio
                state: 'playing'
            card:
              type: custom:mini-media-player
              entity: media_player.master_bedroom_audio
              artwork: cover
      ## Lights ##
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.dining_room_light
              - type: light
                entity: light.living_room_lights
          # - type: horizontal-stack
          #   cards:
          #     - type: light
          #       entity: light.bedroom_lights
          #     - type: light
          #       entity: light.scrub_room
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.master_suite_lights
              - type: light
                entity: light.kitchen_light
      - type: weather-forecast
        entity: weather.dark_sky
      # - type: thermostat
      #   entity: climate.thermostat
  - path: alarms
    title: Alarms
    icon: mdi:alarm
    badges:
      - sensor.workday_alarm
      - sensor.weekend_alarm
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - input_boolean.workday_alarm
              - input_number.workday_hours
              - input_number.workday_minutes
          - type: entities
            entities:
              - input_boolean.weekend_alarm
              - input_number.weekend_hours
              - input_number.weekend_minutes
  - path: automations
    title: Automations
    icon: mdi:code-braces
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: button
                name: Bedtime
                tap_action:
                  action: call-service
                  service: pyscript.bedtime
              - type: button
                name: Morning
                tap_action:
                  action: call-service
                  service: pyscript.morning
              - type: button
                name: Shutdown
                tap_action:
                  action: call-service
                  service: pyscript.shutdown
          - type: entities
            entities:
              - script.be_right_back
              - script.led_strip_turn_on
              - script.play_all_music
              - script.play_chill_music
              - script.volume_down
              - script.volume_up
          - type: entities
            entities:
              - input_boolean.bedtime
              - input_boolean.enable_presence_automations
      - type: entities
        entities:
          - automation.arrive_home_jenni
          - automation.arrive_home_justin
          - automation.leave_home_jenni
          - automation.leave_home_justin
          - automation.living_room_tv_started
          - automation.bedroom_tv_started
          - automation.bedroom_tv_idle
          - automation.music_started
          - automation.receiver_input_change_video
          - automation.receiver_input_change_audio
          - automation.night_no_one_home
          - automation.sunset
          # - automation.update_google_assistant
          # - automation.update_led_strip_colour_when_hue_colour_changed
          # - automation.periodically_change_the_led_strip_to_a_random_colour
          # - automation.its_christmas
  - path: media
    title: Media Control
    icon: mdi:music
    cards:
      - type: custom:mini-media-player
        entity: media_player.home_audio
        icon: mdi:music
        group: true
        source: icon
        info: short
      - type: custom:mini-media-player
        entity: media_player.master_bedroom_audio
        icon: mdi:music
        group: true
      - type: custom:mini-media-player
        entity: media_player.master_bathroom_speaker
        icon: mdi:music
        group: true
      - type: custom:mini-media-player
        entity: media_player.bathroom_speaker
        icon: mdi:music
        group: true
      - type: custom:mini-media-player
        entity: media_player.living_room_audio
        icon: mdi:music
        group: true
      - type: custom:mini-media-player
        entity: media_player.denon_avr_x1300w
        group: true
      - type: custom:mini-media-player
        entity: media_player.master_suite_audio
        icon: mdi:music
        group: true
        source: icon
        info: short
      - type: custom:mini-media-player
        entity: media_player.master_bathroom_speaker
        icon: mdi:music
        group: true
      - type: custom:mini-media-player
        entity: media_player.fake_home_audio
        icon: mdi:music
        group: true
        source: icon
        info: short
  - path: video
    title: TV
    icon: mdi:youtube
    cards:
      - type: custom:upcoming-media-card
        entity: sensor.sonarr_upcoming_media
