## Expose these items ##
# Scripts
script.play_all_music:
  name: All music
  expose: true
script.are_the_fish_fed:
  expose: true
script.bedtime:
  expose: true
script.play_chill_music:
  name: Chill music
  expose: true
script.did_the_things:
  name: Did the things
  expose: true
script.fed_the_fish:
  name: Fish fed
  expose: true
script.morning:
  name: Good morning
  expose: true
script.shutdown:
  expose: true
script.watered_the_plants:
  name: Watered plants
  expose: true
script.be_right_back:
  expose: true
script.shower_time:
  name: Shower Time
  expose: true
script.select_source_switch:
  expose: true
script.select_source_pc:
  expose: true
script.select_source_shield:
  expose: true
script.select_source_audio:
  expose: true
# Lights
light.master_suite_lights:
  expose: true
light.bathroom_lights:
  expose: true
light.betta_light:
  expose: true
light.living_room_lamp:
  expose: true
light.living_room_light:
  expose: true
light.living_room_lights:
  expose: true
# Media
switch.justins_pc:
  name: My PC
  expose: true
media_player.lg_tv:
  name: TV
  expose: true
media_player.denon_avrx1300w:
  name: Receiver
  expose: true