- platform: flux_led
  devices:
    192.168.0.28:
      name: LEDs Behind Couch
      mode: rgb
- platform: group
  name: Bedroom Lights
  entities:
    - light.bedroom_light_1
    - light.bedroom_light_2
    - light.closet_light
    - light.office_light
- platform: group
  name: Living Room Lights
  entities:
    - light.living_room_lamp
    - light.leds_behind_couch
- platform: group
  name: Dining Room Lights
  entities:
    - light.dining_light_1
# - platform: group
#   name: Bathroom Lights
#   entities:
#     - light.bathroom_light_1
#     - light.bathroom_light_2
- platform: group
  name: Master Suite Lights
  entities:
    - light.bedroom_lights
    # - light.bathroom_lights
- platform: group
  name: All Lights
  entities:
    - light.master_suite_lights
    - light.living_room_lights
    - light.fairy_lights
