- platform: group
  name: Bedroom Lights
  entities:
    - light.bedroom_light_1
    - light.bedroom_light_2
    - light.closet_light
    - light.office_light
- platform: group
  name: Living Room Lights
  entities:
    - light.living_room_lamp
    - light.leds_behind_couch
    - light.leds_behind_tv
    - light.kitchen_hall_light
- platform: group
  name: Dining Room Lights
  entities:
    - light.dining_room_light
- platform: group
  name: All Lights
  entities:
    - light.bedroom_lights
    - light.living_room_lights
    - light.dining_room_light
    - light.kitchen_light
