- platform: group
  name: Master Suite Lights
  entities:
    - light.bedroom_light_1
    - light.bedroom_light_2
    - light.bedroom_light_3
    - light.bathroom
    - light.master_bathroom_leds
- platform: group
  name: All Lights
  entities:
    - light.master_suite_lights
    - light.living_room
    - light.fairy_lights