- platform: group
  name: Nightstand Lights
  entities:
    - light.bedroom_light_1
    - light.bedroom_light_2
- platform: group
  name: Bedroom Lights
  entities:
    - light.bedroom_light_1
    - light.bedroom_light_2
    - light.bedroom_wall_lights
    - light.office_light
    - light.closet_light
    - light.case_light_leds
- platform: group
  name: Living Room LEDs
  entities:
    - light.leds_behind_couch
    - light.leds_behind_tv
- platform: group
  name: Living Room Lights
  entities:
    - light.living_room_lamp
    - light.leds_behind_couch
    - light.leds_behind_tv
- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen_light
    - light.kitchen_hall_light
- platform: group
  name: Dining Room Lights
  entities:
    - light.dining_room_light
- platform: group
  name: All Lights
  entities:
    - light.bedroom_light_1
    - light.bedroom_light_2
    - light.bedroom_wall_lights
    - light.office_light
    - light.closet_light
    - light.case_light_leds
    - light.living_room_lamp
    - light.leds_behind_couch
    - light.leds_behind_tv
    - light.kitchen_light
    - light.kitchen_hall_light
    - light.dining_room_light