- platform: template
  lights:
    betta_light:
      friendly_name: Betta Light
      icon_template: mdi:fish
      value_template: '{{ is_state("switch.betta_light", "on") }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.betta_light
      turn_off:
        service: switch.turn_off
        entity_id: switch.betta_light