- platform: template
  lights:
    betta_light:
      friendly_name: Betta Light
      icon_template: mdi:fish
      value_template: '{{ is_state("switch.betta_light_switch", "on") }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.betta_light_switch
      turn_off:
        service: switch.turn_off
        entity_id: switch.betta_light_switch
    master_bathroom_leds:
      friendly_name: Master Bathroom LEDs
      icon_template: mdi:led-strip
      value_template: '{{ is_state("switch.master_bathroom_led_switch", "on") }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.master_bathroom_led_switch
      turn_off:
        service: switch.turn_off
        entity_id: switch.master_bathroom_led_switch
    fish_light:
      friendly_name: Fish Light
      icon_template: mdi:fish
      value_template: '{{ is_state("switch.fish_light_switch", "on") }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.fish_light_switch
      turn_off:
        service: switch.turn_off
        entity_id: switch.fish_light_switch
    fairy_lights:
      friendly_name: Fairy Lights
      value_template: '{{ is_state("switch.fairy_lights_switch", "on") }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.fairy_lights_switch
      turn_off:
        service: switch.turn_off
        entity_id: switch.fairy_lights_switch