- platform: template
  lights:
    betta_light:
      friendly_name: Betta Light
      icon_template: mdi:fish
      value_template: '{{ is_state("switch.betta_light", "on") }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.betta_light
      turn_off:
        service: switch.turn_off
        entity_id: switch.betta_light
    fish_light:
      friendly_name: Fish Light
      icon_template: mdi:fish
      value_template: '{{ is_state("switch.fish_light", "on") }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.fish_light
      turn_off:
        service: switch.turn_off
        entity_id: switch.fish_light
    fairy_lights:
      friendly_name: Fairy Lights
      value_template: '{{ is_state("switch.fairy_lights", "on") }}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.fairy_lights
      turn_off:
        service: switch.turn_off
        entity_id: switch.fairy_lights