- platform: mqtt_room
  device_id: !secret justin_phone_device_id
  name: >
    ESP Justin's Phone
  state_topic: !secret justin_phone_topic
  unique_id: esp_justin_phone
  timeout: 10
  away_timeout: 60
- platform: mqtt_room
  device_id: !secret justin_watch_device_id
  name: >
    ESP Justin's Watch
  state_topic: !secret justin_watch_topic
  unique_id: esp_justin_watch
  timeout: 10
  away_timeout: 60
- platform: mqtt_room
  device_id: !secret jenni_phone_device_id
  name: >
    ESP Jenni's Phone
  state_topic: !secret jenni_phone_topic
  unique_id: esp_jenni_phone
  timeout: 10
  away_timeout: 60
- platform: mqtt_room
  device_id: !secret jenni_watch_device_id
  name: >
    ESP Jenni's Watch
  state_topic: !secret jenni_watch_topic
  unique_id: esp_jenni_watch
  timeout: 10
  away_timeout: 60