# services.yaml
volume_fade:
  description: Slowly transition the volume to an end point.
  fields:
    step_size:
      description: How quickly in volume percentage to transition the volume.
      example: 1
    end_volume:
      description: The volume to transition to in percentage.
      example: 60