- alias: Bedroom On
  trigger:
    platform: state
    entity_id: switch.bedroom_light
    from: 'off'
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.bedroom_lamp

- alias: Bedroom Off
  trigger:
    platform: state
    entity_id: switch.bedroom_light
    from: 'on'
    to: 'off'
  action:
    service: switch.turn_off
    entity_id: switch.bedroom_lamp