- alias: Bedroom Off
  trigger:
    platform: state
    entity_id: light.bedroom_light
    from: 'on'
    to: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.bedroom_light
    - service: light.toggle
      entity_id: light.bedroom_light