- alias: Update temperature target
  trigger:
    platform: state
    entity_id: sensor.target_temp
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.thermostat_target_temp
        value: '{{ states("sensor.target_temp") }}'
- alias: Update the thermostat temperature/mode
  trigger:
    - platform: state
      entity_id: sensor.corrected_target_temp
    - platform: state
      entity_id: sensor.hvac_option_choice
  action:
    - service: climate.set_temperature
      data_template:
        entity_id: climate.thermostat
        temperature: '{{ float(states("sensor.corrected_target_temp")) }}'
        hvac_mode: '{{ states("sensor.hvac_option_choice") }}'