- alias: Sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-00:20:00"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.justin_presence
        state: 'on'
      - condition: state
        entity_id: binary_sensor.jenni_presence
        state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.sunset
- alias: Night No One Home
  trigger:
    platform: time
    at: "23:59:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.justin_presence
        state: 'off'
      - condition: state
        entity_id: binary_sensor.jenni_presence
        state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.shutoff
      data:
        variables:
          bedtime: false
- alias: Startup
  trigger:
    platform: homeassistant
    event: start
  action:
    #- service: google_assistant.request_sync
    #- service: frontend.set_theme
    #  data:
    #    name: dark_theme
    - service: script.turn_on
      entity_id: script.enable_presence_on_boot
