- alias: Sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-00:20:00"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: device_tracker.justins_phone
        state: 'home'
      - condition: state
        entity_id: device_tracker.jennis_phone
        state: 'home'
  action:
    - service: switch.turn_on
      entity_id: switch.fairy_lights
    - service: switch.turn_on
      entity_id: switch.living_room_lamp

- alias: Night No One Home
  trigger:
    platform: time
    at: "23:59:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.justins_phone
        state: 'not_home'
      - condition: state
        entity_id: device_tracker.jennis_phone
        state: 'not_home'
  action:
    - service: script.turn_on
      entity_id: script.shutoff