- alias: Betta Light On
  trigger:
    - platform: time
      at: "10:00:00"
    - platform: time
      at: "18:30:00"
  action:
    - service: light.turn_on
      entity_id: light.betta_light

- alias: Betta Light Off
  trigger:
    - platform: time
      at: "13:00:00"
    - platform: time
      at: "22:00:00"
  action:
    - service: light.turn_off
      entity_id: light.betta_light

- alias: CO2 On
  trigger:
    - platform: time
      at: "09:00:00"
    - platform: time
      at: "17:30:00"
  action:
    - service: switch.turn_on
      entity_id: switch.fish_solenoid

- alias: CO2 Off
  trigger:
    - platform: time
      at: "13:00:00"
    - platform: time
      at: "22:00:00"
  action:
    - service: switch.turn_off
      entity_id: switch.fish_solenoid

- alias: Check if plants watered and fish fed
  trigger:
    - platform: time
      at: "12:00:00"
  action:
    - service: script.turn_on
      entity_id: script.forgot_to_water_the_plants
    - service: script.turn_on
      entity_id: script.forgot_to_feed_fish

- alias: Notify when fish have been fed
  trigger:
    - platform: state
      entity_id: input_boolean.fish_fed_tracker
      to: 'on'
  condition:
    condition: time
    after: "12:00:00"
  action:
    - service: script.turn_on
      entity_id: script.notify_fish_fed

- alias: Notify when plants have been watered
  trigger:
    - platform: state
      entity_id: input_boolean.plants_watered_tracker
      to: 'on'
  condition:
    condition: time
    after: "12:00:00"
  action:
    - service: script.turn_on
      entity_id: script.notify_plants_watered