- alias: Bedroom motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_sensor_motion_detection
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.bedtime
      state: 'off'
    - condition: time
      after: "10:00:00"
      before: "23:30:00"
  action:
    service: light.turn_on
    entity_id: light.bedroom_lights
- alias: Enable bedroom motion detected
  trigger:
    platform: state
    entity_id: light.bedroom_lights
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.bedtime
        state: 'off'
      - condition: state
        entity_id: automation.bedroom_motion_detected
        state: 'off'
  action:
    service: automation.turn_on
    entity_id: automation.bedroom_motion_detected
- alias: Bedroom motion no longer detected
  trigger:
    platform: state
    entity_id: sensor.bedroom_presence
    to: 'off'
    for:
      minutes: 5
  action:
    - service: light.turn_off
      entity_id: light.bedroom_lights
    - service: light.turn_off
      entity_id: light.closet_light
- alias: Bedroom lights on
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 14
      label: "Scene 001"
      value: 0
  action:
    service: light.turn_on
    entity_id: light.bedroom_lights
- alias: Bedroom lights on full
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 14
      label: "Scene 001"
      value: 3
  action:
    service: light.turn_on
    data:
      entity_id: light.bedroom_lights
      brightness_pct: 100
- alias: Bedroom lights off
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 14
      label: "Scene 002"
      value: 0
  action:
    service: light.turn_off
    entity_id: light.bedroom_lights
- alias: Living room lights on
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 13
      label: "Scene 001"
      value: 0
  action:
    service: light.turn_on
    entity_id: light.living_room_lights
- alias: Living room lights off
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 13
      label: "Scene 002"
      value: 0
  action:
    service: light.turn_off
    entity_id: light.living_room_lights