- alias: Update LED Strip Colour When Hue Colour Changed
  trigger:
    platform: state
    entity_id: sensor.hue_colour
  action:
    service: light.turn_on
    data_template:
      entity_id: light.led_strip
      brightness: >
        {% if states.light.kitchen.attributes["brightness"]|int > 205 %}
          205
        {% else %}
          {{ states.light.kitchen.attributes["brightness"] }}
        {% endif %}
      rgb_color: ['{{ states.light.kitchen.attributes["rgb_color"][0] }}', '{{ states.light.kitchen.attributes["rgb_color"][1] }}', '{{ states.light.kitchen.attributes["rgb_color"][2] }}']
- alias: Periodically Change the LED Strip to a Random Colour
  trigger:
    platform: time_pattern
    minutes: '/5'
  condition:
    condition: state
    entity_id: light.led_strip
    state: 'on'
  action:
    service: script.turn_on
    entity_id: script.led_strip_set_random_colour
- alias: It's Christmas
  initial_state: false
  trigger:
    platform: time_pattern
    seconds: '/2'
  action:
    service: script.turn_on
    entity_id: script.led_strip_christmas
- alias: Hue Remote Button Press
  trigger:
    platform: state
    entity_id: sensor.hue_remote_last_update
  action:
    service: script.turn_on
    entity_id: script.hue_remote
