# - alias: Update LED Strip Colour When Hue Colour Changed
#   trigger:
#     platform: state
#     entity_id: sensor.hue_colour
#   action:
#     service: light.turn_on
#     data_template:
#       entity_id: light.led_strip
#       brightness: >
#         {% if state_attr("light.living_room_lights", "brightness")|int > 205 %}
#           205
#         {% else %}
#           {{ state_attr("light.living_room_lights", "brightness") }}
#         {% endif %}
#       rgb_color: ['{{ state_attr("light.living_room_lights", "rgb_color")[0] }}', '{{ state_attr("light.living_room_lights", "rgb_color")[1] }}', '{{ state_attr("light.living_room_lights", "rgb_color")[2] }}']
# - alias: Periodically Change the LED Strip to a Random Colour
#   trigger:
#     platform: time_pattern
#     minutes: '/5'
#   condition:
#     condition: state
#     entity_id: light.led_strip
#     state: 'on'
#   action:
#     service: script.turn_on
#     entity_id: script.led_strip_set_random_colour
# - alias: It's Christmas
#   initial_state: false
#   trigger:
#     platform: time_pattern
#     seconds: '/2'
#   action:
#     service: script.turn_on
#     entity_id: script.led_strip_christmas
# - alias: Hue Remote On Button Press
#   trigger:
#     device_id: b4f4a268989eb005ffe65f9079a1f59e
#     domain: hue
#     platform: device
#     type: remote_button_short_release
#     subtype: turn_on
#   action:
#     service: light.toggle
#     entity_id: light.master_suite_lights
# - alias: Hue Remote Dim Up Button Press
#   trigger:
#     platform: device
#     device_id: b4f4a268989eb005ffe65f9079a1f59e
#     domain: hue
#     type: remote_button_short_release
#     subtype: dim_up
#   action:
#     service: light.toggle
#     entity_id: light.bedroom_lights
# - alias: Hue Remote Dim Down Button Press
#   trigger:
#     platform: device
#     device_id: b4f4a268989eb005ffe65f9079a1f59e
#     domain: hue
#     type: remote_button_short_release
#     subtype: dim_down
#   action:
#     service: light.toggle
#     entity_id: light.bathroom_lights
# - alias: Hue Remote Off Button Press
#   trigger:
#     platform: device
#     device_id: b4f4a268989eb005ffe65f9079a1f59e
#     domain: hue
#     type: remote_button_short_release
#     subtype: turn_off
#   action:
#     service: light.toggle
- alias: Bedroom motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_sensor_home_security_motion_detection
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.bedtime
      state: 'off'
    - condition: time
      before: "23:30:00"
  action:
    service: light.turn_on
    data_template:
      entity_id: >-
        {% if is_state("input_boolean.bedtime", "on") %}
          light.bathroom_lights
        {% else %}
          light.master_suite_lights
        {% endif %}
#      rgb_color: '{{ states("sensor.lights_colour") }}'
      brightness: '{{ states("sensor.lights_brightness")|int }}'
- alias: Bedroom motion no longer detected
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_sensor_home_security_motion_detection
    to: 'off'
    for:
      minutes: 10
  action:
    service: light.turn_off
    entity_id: light.master_suite_lights
- alias: Light settings changed
  trigger:
    platform: state
    entity_id: sensor.lights_colour
  condition:
    condition: state
    entity_id: light.master_suite_lights
    state: 'on'
  action:
    service: light.turn_on
    data_template:
      entity_id: >-
        {% if is_state("input_boolean.bedtime", "on") %}
          light.bathroom_lights
        {% else %}
          light.master_suite_lights
        {% endif %}
      rgb_color: '{{ states("sensor.lights_colour") }}'
      brightness: '{{ states("sensor.lights_brightness") }}'
      transition: 15