### Media Starting
- alias: Music Started
  trigger:
    platform: state
    entity_id: binary_sensor.home_audio_playing
    to: 'on'
  action:
    - service: media_player.select_source
      data:
        entity_id: media_player.denon_avr_x1300w
        source: CastAudio
- alias: Living Room TV Started
  trigger:
    - platform: state
      entity_id: media_player.shield
      from: 'idle'
      to: 'paused'
    - platform: state
      entity_id: media_player.shield
      from: 'idle'
      to: 'playing'
    - platform: state
      entity_id: media_player.shield
      from: 'off'
      to: 'paused'
    - platform: state
      entity_id: media_player.shield
      from: 'off'
      to: 'playing'
    - platform: state
      entity_id: media_player.shield
      from: 'off'
      to: 'idle'
    - platform: state
      entity_id: media_player.shield
      from: 'standby'
      to: 'idle'
    - platform: state
      entity_id: media_player.shield_cast
      to: 'playing'
  action:
      - service: media_player.select_source
        data:
          entity_id: media_player.denon_avr_x1300w
          source: Shield
      - service: media_player.turn_on
        entity_id: media_player.vizio
- alias: Bedroom TV Started
  trigger:
    platform: state
    entity_id: media_player.bedroom_tv
    to: 'playing'
  action:
    - service: media_player.turn_off
      data_template:
        entity_id: '{{ states("sensor.media_player_output") }}'
- alias: Bedroom TV Idle
  trigger:
    platform: state
    entity_id: media_player.bedroom_tv
    to: 'idle'
    for:
      minutes: 10
  action:
    - service: media_player.turn_off
      entity_id: media_player.bedroom_tv

### Receiver Select ###
- alias: Receiver Input Change Video
  trigger:
    - platform: state
      entity_id: media_player.denon_avr_x1300w
      to: PC
    - platform: state
      entity_id: media_player.denon_avr_x1300w
      to: Shield
    - platform: state
      entity_id: media_player.denon_avr_x1300w
      to: Switch
  action:
    - service: media_player.turn_on
      entity_id: media_player.vizio
- alias: Receiver Input Change Audio
  trigger:
    - platform: state
      entity_id: media_player.denon_avr_x1300w
      to: CastAudio
  action:
    - service: media_player.turn_off
      entity_id: media_player.vizio