- alias: Music Started 1
  trigger:
    platform: state
    entity_id: sensor.media_source
    to: 'CastAudio'
  action:
    - service: script.turn_on
      entity_id: script.switch_to_audio

- alias: Music Started 2
  trigger:
    platform: state
    entity_id: media_player.home_audio
    to: 'playing'
  action:
    - service: script.turn_on
      entity_id: script.switch_to_audio

- alias: Casting Started 1
  trigger:
    platform: state
    entity_id: media_player.vizio_smartcast
    to: 'on'
  action:
    - service: script.turn_on
      entity_id: script.switch_to_chromecast

- alias: Casting Started 2
  trigger:
    platform: state
    entity_id: media_player.vizio_smartcast
    to: 'playing'
  action:
    - service: script.turn_on
      entity_id: script.switch_to_chromecast

- alias: Cast music when playing from MPD
  trigger:
    platform: state
    entity_id: media_player.mpd
    from: 'off'
    to: 'playing'
  action:
    - service: script.turn_on
      entity_id: script.stream_mopidy_to_cc

- alias: Restart stream
  trigger:
    platform: state
    entity_id: media_player.home_audio
    from: 'playing'
    to: 'idle'
  action:
    - service: script.turn_on
      entity_id: script.restart_mopidy_stream

- alias: Stop MPD when other device casting
  trigger:
    platform: state
    entity_id: sensor.home_audio_app
    to: 'Spotify'
  action:
    - service: media_player.media_stop
      entity_id: media_player.mpd

- alias: Home audio unavailable for 15 minutes
  trigger:
    platform: state
    entity_id: media_player.home_audio
    to: 'unavailable'
    for:
      minutes: 15
  action:
    service: homeassistant.restart

- alias: Living Room Audio Slider Moved
  trigger:
    platform: state
    entity_id: input_number.living_room_audio_volume
  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.living_room_audio
      volume_level: '{{ states("input_number.living_room_audio_volume")|float }}'

- alias: Bedroom Audio Slider Moved
  trigger:
    platform: state
    entity_id: input_number.bedroom_audio_volume
  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.bedroom_audio
      volume_level: '{{ states("input_number.bedroom_audio_volume")|float }}'

- alias: Bathroom Audio Slider Moved
  trigger:
    platform: state
    entity_id: input_number.bathroom_audio_volume
  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.bathroom_speaker
      volume_level: '{{ states("input_number.bathroom_audio_volume")|float }}'

- alias: Media Input Select Changed
  trigger:
    platform: state
    entity_id: input_select.media_select
  action:
    service: script.turn_on
    entity_id: script.media_input_select

- alias: Media Volume Slider Moved
  trigger:
    platform: state
    entity_id: input_number.media_audio_volume
  action:
    service: script.turn_on
    entity_id: script.media_volume_changed

- alias: Media Source Changed
  trigger:
    platform: state
    entity_id: sensor.media_source
  action:
    - service: script.turn_on
      entity_id: script.update_media_select_source

- alias: Media Volume Changed
  trigger:
    platform: state
    entity_id: sensor.media_volume
  action:
    - service: script.turn_on
      entity_id: script.update_media_volume_slider