### Media Starting
- alias: Music Started 1
  trigger:
    platform: state
    entity_id: sensor.media_player_status
    to: 'playing'
  condition:
    condition: template
    value_template: >
      {% if is_state("input_select.receiver_source_select", "Cast Audio") %}
        false
      {% else %}
        true
      {% endif %}
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.receiver_source_select
        option: 'Cast Audio'
- alias: Music Started 2
  trigger:
    platform: state
    entity_id: sensor.media_player_status
    to: 'playing'
  condition:
    condition: state
    entity_id: input_select.receiver_source_select
    state: 'Cast Audio'
  action:
    - service: script.turn_on
      entity_id: script.media_input_select
- alias: Living Room TV Started 1
  trigger:
    - platform: state
      entity_id: media_player.shield
      from: 'off'
      to: 'idle'
    - platform: state
      entity_id: media_player.shield
      from: 'idle'
      to: 'playing'
  condition:
    condition: template
    value_template: >
      {% if is_state("input_select.receiver_source_select", "Shield") %}
        false
      {% else %}
        true
      {% endif %}
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.receiver_source_select
        option: 'Shield'
- alias: Living Room TV Started 2
  trigger:
    - platform: state
      entity_id: media_player.shield
      from: 'off'
      to: 'idle'
    - platform: state
      entity_id: media_player.shield
      from: 'idle'
      to: 'playing'
  condition:
    condition: state
    entity_id: input_select.receiver_source_select
    state: 'Shield'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.receiver_source_select
        option: 'Shield'
- alias: Bedroom TV Started
  trigger:
    platform: state
    entity_id: media_player.bedroom_tv
    to: 'playing'
  action:
    - service: media_player.turn_off
      data_template:
        entity_id: '{{ states("sensor.media_player_output") }}'

### Volume Sliders ##
- alias: Living Room Audio Slider Moved
  trigger:
    platform: state
    entity_id: input_number.living_room_audio_volume
  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.living_room_audio
      volume_level: '{{ states("input_number.living_room_audio_volume")|float / 100 }}'
- alias: Bedroom Audio Slider Moved
  trigger:
    platform: state
    entity_id: input_number.master_bedroom_audio_volume
  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.master_bedroom_audio
      volume_level: '{{ states("input_number.master_bedroom_audio_volume")|float / 100 }}'
- alias: Master Bathroom Audio Slider Moved
  trigger:
    platform: state
    entity_id: input_number.master_bathroom_audio_volume
  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.master_bathroom_speaker
      volume_level: '{{ states("input_number.master_bathroom_audio_volume")|float / 100 }}'
- alias: Bathroom Audio Slider Moved
  trigger:
    platform: state
    entity_id: input_number.bathroom_audio_volume
  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.bathroom_speaker
      volume_level: '{{ states("input_number.bathroom_audio_volume")|float / 100 }}'
- alias: Receiver Volume Slider Moved
  trigger:
    platform: state
    entity_id: input_number.receiver_audio_volume
  action:
    service: script.turn_on
    entity_id: script.set_receiver_volume
- alias: Chromecast Volume Slider Moved
  trigger:
    platform: state
    entity_id: input_number.chromecast_audio_volume
  action:
    service: script.turn_on
    entity_id: script.set_chromecast_volume

### I/O Select ###
- alias: Media Input Select Changed
  trigger:
    platform: state
    entity_id: input_select.receiver_source_select
  action:
    service: script.turn_on
    entity_id: script.media_input_select
- alias: Media Output Changed
  trigger:
    platform: state
    entity_id: input_select.media_output_select
  action:
    - service: spotcast.start
      data_template:
        device_name: '{{ states("input_select.media_output_select") }}'