- alias: Leave Home Justin
  trigger:
    platform: state
    entity_id: binary_sensor.justin_presence
    from: 'on'
    to: 'off'
  condition:
    condition: state
    entity_id: input_boolean.enable_presence_automations
    state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.leave_home_justin
    - service: script.turn_on
      entity_id: script.leave_home

- alias: Leave Home Jenni
  trigger:
    platform: state
    entity_id: binary_sensor.jenni_presence
    from: 'on'
    to: 'off'
  condition:
    condition: state
    entity_id: input_boolean.enable_presence_automations
    state: 'on'
  action:
    service: script.turn_on
    entity_id: script.leave_home

- alias: Leave Home Jayden
  initial_state: false
  trigger:
    platform: state
    entity_id: binary_sensor.jayden_presence
    from: 'on'
    to: 'off'
  condition:
    condition: state
    entity_id: input_boolean.enable_presence_automations
    state: 'on'
  action:
    service: script.turn_on
    entity_id: script.leave_home

- alias: Arrive Home Justin
  initial_state: false
  trigger:
    platform: state
    entity_id: binary_sensor.justin_presence
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.enable_presence_automations
    state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.arrive_home_justin
    - service: script.turn_on
      entity_id: script.arrive_home

- alias: Arrive Home Jenni
  initial_state: false
  trigger:
    platform: state
    entity_id: binary_sensor.jenni_presence
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.enable_presence_automations
    state: 'on'
  action:
    service: script.turn_on
    entity_id: script.arrive_home

- alias: Arrive Home Jayden
  initial_state: false
  trigger:
    platform: state
    entity_id: binary_sensor.jayden_presence
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.enable_presence_automations
    state: 'on'
  action:
    service: script.turn_on
    entity_id: script.arrive_home