- alias: Leave Home Justin
  trigger:
    platform: state
    entity_id: binary_sensor.justin_presence
    from: 'on'
    to: 'off'
  action:
    service: script.turn_on
    entity_id: script.wifi_check

- alias: Leave Home Jenni
  trigger:
    platform: state
    entity_id: binary_sensor.jenni_presence
    from: 'on'
    to: 'off'
  condition:
    condition: state
    entity_id: binary_sensor.justin_presence
    state: 'off'
  action:
    service: script.turn_on
    entity_id: script.shutoff
    data:
      variables:
        bedtime: false

- alias: Arrive Home Justin
  trigger:
    platform: state
    entity_id: binary_sensor.justin_presence
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: binary_sensor.jenni_presence
    state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.arrive_home
    - service: script.turn_on
      entity_id: script.arrive_home_justin

- alias: Arrive Home Jenni
  trigger:
    platform: state
    entity_id: binary_sensor.jenni_presence
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: binary_sensor.justin_presence
    state: 'off'
  action:
    service: script.turn_on
    entity_id: script.arrive_home